"""empty message

Revision ID: 9941b447d453
Revises: cb13d9a58481
Create Date: 2022-05-25 14:19:40.300873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9941b447d453'
down_revision = 'cb13d9a58481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=512), nullable=True))
    op.add_column('artists', sa.Column('look_for_venues', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_desc', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('website_link', sa.String(length=512), nullable=True))
    op.add_column('venues', sa.Column('look_for_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_desc')
    op.drop_column('venues', 'look_for_talent')
    op.drop_column('venues', 'website_link')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'seeking_desc')
    op.drop_column('artists', 'look_for_venues')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
